const CHANGE_ACTIVE_NAV = 'CHANGE_ACTIVE_NAV';
const CHANGE_DICOM_URLS = 'CHANGE_DICOM_URLS';
const CHANGE_USER_DETAILS = 'CHANGE_USER_DETAILS';

module.exports = { CHANGE_ACTIVE_NAV, CHANGE_DICOM_URLS, CHANGE_USER_DETAILS };